version: '3.7'
services:
    sf-kb:
        image: openlink/virtuoso-opensource-7:latest
        container_name: kb
        environment:
            - DBA_PASSWORD=mysecret
        ports:
            - '1111:1111'
            - '8890:8890'
        volumes:
            - './pwd:/database'
    dr-api:
        image: collaborativedhs/sf-datareceiver:v2.0
        container_name: dr
        ports:
            - '8088:8080'    
        volumes:
            - .:/logs       
    sf-api:
        image: collaborativedhs/semantic_framework:v2.3
        depends_on:
            - sf-kb
            - dr-api
        ports:
            - '8087:8080'    
        volumes:
            - ./config/configuration.json:/config/configuration.json
            - .:/logs
            - ./config/keycloak_configuration.json:/config/keycloak_configuration.json
        environment:
            - 'KB_ADDRESS=jdbc:virtuoso://sf-kb:1111'
            - 'KB_ADDRESS_REPO=http://sf-kb:8890/'
            - 'KB_ADDRESS_RETRIEVE=http://sf-kb:8890/sparql'
            - 'DR_ADDRESS=http://dr-api:8080/DataReceiver/webresources/'   
            